base/urls.py
from django.urls import path
from . import views
app_name = 'base'
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('shop/', views.shop_page, name='shop_page'),
    path('about/', views.about_page, name='about_page'),
    path('contact/', views.contact_page, name='contact_page'),


    path('shop/<int:pk>/', views.detail_product, name='detail_product_page'),
    path('cart/', views.cart_page, name='cart_page'),
    path('shop/update_product/',views.update_product,name='update_product'),
]

ecommerceProj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('dashboard/', include('dashboard.urls'),),
    path('', include('user.urls'),),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from . import views
app_name = 'user' 
urlpatterns = [
    path('register/',views.register_user,name = 'register'),
    path('login/',views.login_user,name = 'login'),
    path('logout/',views.logout_user,name = 'logout'),

]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

user/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from base.models import Customer

# Create your views here.


def register_user(request):
    form = UserRegisterForm()
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            customer = Customer.objects.create(user=user,name = user.username,email=user.email)
            customer.save()
            login(request,user)
            return redirect('base:home_page')
        else:
            messages.error(request, 'An error occurred during registration')
    context = {'form': form}
    return render(request,'user/login_register.html',context)

def login_user(request):
    page = 'login'
   
    if request.user.is_authenticated:
         if request.user.is_superuser:
            return redirect('dashboard:index')
         return redirect('base:home_page')
    
    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            # check have user or not
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User does not exits')

        # check username nad password
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('base:home_page')
        else:
            messages.error(request, 'Username OR password does not exit')

    context = {'page': page}
    return render(request, 'user/login_register.html', context)

def logout_user(request):
    logout(request)
    return redirect('base:home_page')

user/templates/user/login_register.html
{% extends 'base/main.html' %} {% block title %} Register Page {% endblock title%} 
{% block content %}
<section class="section-p1">
  {% if page == 'login' %}
  <div class="form__group_all">
    <form class="form__group1" action="" method="POST">
      {% csrf_token %}
      <div class="form__group2"> 
        <div class="form__group3">
          <h1 class="titlelog_reg">
            Login your Account
          </h1>
          <label for="username">Username</label>
          <input id="username"class="login_input" style="margin-bottom: 10px;" name="username" type="text"placeholder="e.g. dennis_ivy"/>
          <label for="password">Password</label>
          <input id="password" name="password" type="password" class="login_input" style="margin-bottom: 10px;" placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"/>
          <button class="normalBtn" type="submit">Login</button>
        </div>  
      </div>
    </form>
    <div class="auth__action form__group1">
      <p>Haven't account yet?</p>
      <button class="normalBtn" style="margin-left: 10px;"><a style="text-decoration: none; color: white;" href="{% url 'user:register' %}">Register</a></button>
    </div>
  </div>
  {% else %}
  <div class="form__group_all">
    <form class="form__group1" action="" method="POST">
      {% csrf_token %} 
      <div class="form__group4">
        <h1 class="titlelog_reg">
          Register your Account
        </h1>
        {% for field in form %}
      <div class="form__group3" >
        <label style="font-size: 0.7rem;" for="room_name">{{field.label}}</label>

        <span  style="margin-bottom: 10px;">{{field}}</span>
      </div>
      {% endfor %}
      <button type="submit" class="normalBtn">Register</button>
      </div>      
    </form>
    <div class="auth__action form__group1">
      <p>Already have account t?</p>
      <button class="normalBtn" style="margin-left: 10px;">
        <a style="text-decoration: none; color: white;"  href="{% url 'user:login' %}">LogIn</a>
      </button> 
    </div>
  </div>


  {% endif %}
</section>
{% endblock content %}