base/urls.py
from django.urls import path
from . import views
app_name = 'base'
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('shop/', views.shop_page, name='shop_page'),
    path('about/', views.about_page, name='about_page'),
    path('contact/', views.contact_page, name='contact_page'),


    path('shop/<int:pk>/', views.detail_product, name='detail_product_page'),
    path('cart/', views.cart_page, name='cart_page'),
    path('shop/update_product/',views.update_product,name='update_product'),
]

dashboard/urls.py
from django.urls import path
from . import views
app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='index'),
    path('insert-product/',views.insert_product,name='insert-product'),
    path('update_product/<int:pk>/',views.update_product,name='update_product'),
    path('remove_product/<int:pk>/',views.remove_product,name='remove_product'),
]

ecommerceProj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('dashboard/', include('dashboard.urls'),),
    path('', include('user.urls'),),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django.forms import ModelForm
from base.models import Product


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        

dashboard/views.py
from django.shortcuts import render,redirect
from base.models import Product,Category
from .forms import ProductForm
from django.db.models import Q
# Create your views here.

def index(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    categories = Category.objects.all()
    if q == '':
        products = Product.objects.all()
    else:
        products = Product.objects.filter(
            Q(category__name__icontains=q)|Q(name__icontains=q))
    context = {'products': products, 'categories': categories}
    return render(request,'dashboard/index.html',context)


def insert_product(request):
    form = ProductForm()
    categories = Category.objects.all()
    if request.method == "POST":
        category_name = request.POST.get('category')
        category,created = Category.objects.get_or_create(name=category_name)
        Product.objects.create(
            name=request.POST.get('name'),
            category = category,
            price = request.POST.get('price'),
            in_stock = request.POST.get('in_stock'),
            thumbnail = request.FILES['thumbnail'],
            description = request.POST.get('description'),
        )
        return redirect('dashboard:index')
    context = {'form':form,'categories':categories}
    return render(request,'dashboard/product_form.html',context)


def update_product(request,pk):
    product = Product.objects.get(id=pk)
    form = ProductForm(instance=product)
    categories = Category.objects.all()
    if request.method == "POST":
        category_name = request.POST.get('category')
        category,created = Category.objects.get_or_create(name=category_name)
        product.name = request.POST.get('name')
        product.category = category
        product.in_stock = request.POST.get('in_stock')
        product.thumbnail = request.FILES['thumbnail']
        product.description = request.POST.get('description')
        
        product.save()
       
        return redirect('dashboard:index')
    context = {'form':form,'categories':categories,'product':product}
    return render(request,'dashboard/product_form.html',context)


def remove_product(request,pk):
    product = Product.objects.get(id=pk)
    if request.method == 'POST':
        product.delete()
        return redirect('dashboard:index')
    return render(request,'dashboard/remove_product.html',{'obj': product})
    

dashboard/templates/dashboard/index.html
{% extends 'base/main.html' %} 
{% block title %} Admin Dashboard {% endblock title%} 
{% block content %}
<section id="product1" class="section-p1">
  <div>
    <form action="" method="GET">
      <input type="text" placeholder="Search..." name="q">
      <button type="submit">Search</button>
    </form>
  </div>
  <ul id="category">
    <li>
      <a href="{% url 'dashboard:index' %}">All</a>
    </li>
    {% for category in categories %}
    <li>
      <a id="ab" href="{% url 'dashboard:index'%}?q={{category.name}}"> {{category.name}} </a>
    </li>
    {% endfor %}
  </ul>
  <div>
    <a href="{% url 'dashboard:insert-product' %}">Insert Product</a>
  </div>
  <div class="pro-container">
    {% for product in products %}
    <div class="pro">
      {% if product.thumbnail %}
      <img src="{{product.thumbnail.url}}" alt="Product_image" />
      {% endif %}
      <div class="des">
        <span>{{product.category}}</span>
        <h5>{{product.name}}</h5>
        <h4>${{product.price}}</h4>
      </div>
      <a href="{% url 'dashboard:update_product' product.id  %}">Update product</a>
      {% if request.user.is_superuser %}
      <a href="{% url 'dashboard:remove_product' product.id  %}">Remove product</a>
      {% endif %}
    </div>
    {% endfor %}
  </div>
</section>
{% endblock content %}

dashboard/templates/dashboard/product_form.html
{% extends 'base/main.html' %}
{% block title %} Admin Dashboard {% endblock title%}
{% block content %}
    <section class="section-p1">
        <div>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form__group">
                  <div class="form__group">
                    <label for="room_name">Product Name</label>
                    {{form.name}}
                  </div>
                    <label for="room_topic">Product Categories</label>
                    <input required type="text" value="{{product.category.name}}" name="category" list="topic-list" />
                    <datalist id="topic-list">
                      <select id="room_topic">
                        {% for category in categories %}
                        <option value="{{category.name}}">{{category.name}}</option>
                        {% endfor %}
                      </select>
                    </datalist>
                  </div>
                  <div class="form__group">
                    <label for="room_description">Product price</label>
                    {{form.price}}
                  </div>
                  <div class="form__group">
                    <label for="room_description">Product In stock</label>
                    {{form.in_stock}}
                  </div>
                  <div class="form__group">
                    <label for="room_description">Product Image</label>
                    {{form.thumbnail}}
                  </div>
                  <div class="form__group">
                    <label for="room_description">Product Description</label>
                    {{form.description}}
                  </div>
                  <div class="form__action">
                    <a class="btn btn--dark" href="{% url 'dashboard:index' %}">Cancel</a>
                    <button class="btn btn--main" type="submit">Submit</button>
                  </div>
            </form>
        </div>
    </section>
{% endblock content %}

dashboard/templates/dashboard/remove_product.html
{% extends 'base/main.html' %}
{% block title %} Admin Dashboard {% endblock title%}
{% block content %}
    <section id="product1" class="section-p1">
        <div class="layout__body">
            <form  action="" method="POST">
                {% csrf_token %}
              <div class="form__group">
                <p>Confirm to remove "{{obj}} from database"?</p>
              </div>
    
              <div class="for__group">
                <input class="btn btn--main" type="submit" value="Confirm" />
              </div>
            </form>
          </div>
        
    </section>
{% endblock content %}