base/urls.py
from django.urls import path
from . import views
app_name = 'base'
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('shop/', views.shop_page, name='shop_page'),
    path('about/', views.about_page, name='about_page'),
    path('contact/', views.contact_page, name='contact_page'),


    path('shop/<int:pk>/', views.detail_product, name='detail_product_page'),
    path('cart/', views.cart_page, name='cart_page'),
    path('shop/update_product/',views.update_product,name='update_product'),
]

dashboard/urls.py
from django.urls import path
from . import views
app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='index'),
    path('insert-product/',views.insert_product,name='insert-product'),
    path('update_product/<int:pk>/',views.update_product,name='update_product'),
    path('remove_product/<int:pk>/',views.remove_product,name='remove_product'),
]

ecommerceProj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('dashboard/', include('dashboard.urls'),),
    path('', include('user.urls'),),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.urls import path
from . import views
app_name = 'user' 
urlpatterns = [
    path('register/',views.register_user,name = 'register'),
    path('login/',views.login_user,name = 'login'),
    path('logout/',views.logout_user,name = 'logout'),

]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    thumbnail = models.ImageField(default='default_img.png',upload_to='products_pics')
    price = models.DecimalField(max_digits=7, decimal_places=3)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    in_stock = models.IntegerField(default=0)
    description = models.TextField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    

    
    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name
    def save(self,*args, **kwargs):
        super().save()
        img = Image.open(self.thumbnail.path)
        if img.height > 394 or img.width > 394:
            output_size = (394, 394)
            img.thumbnail(output_size)
            img.save(self.thumbnail.path)

class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)
    def __str__(self):
	    return self.name

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return self.id 
    @property
    def get_cart_total(self):
        orderitems = self.orderproduct_set.all()
        total = sum([item.get_total for item in orderitems])
        return total
    @property
    def get_cart_items(self):
        orderitems = self.orderproduct_set.all()
        total = sum([item.quantity for item in orderitems])
        return total

class OrderProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total
    def __str__(self)->str:
        return  self.product.name

base/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from .models import Product, Category, Order, OrderProduct
from django.db.models import Q
import json
from django.http import JsonResponse

# Create your views here.


def home_page(request):
    some_products = Product.objects.all()[0:6]
    context = {'some_products': some_products}
    return render(request, 'base/home.html', context)


def shop_page(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    categories = Category.objects.all()
    if q == '':
        products = Product.objects.all()
    else:
        products = Product.objects.filter(
            Q(category__name__icontains=q)|Q(name__icontains=q))
    paginator = Paginator(products, 10)
    page_number = request.GET.get("page")
    page_product = paginator.get_page(page_number)
    context = {'page_product': page_product, 'categories': categories}
    return render(request, 'base/shop.html', context)

def about_page(request):
    return render(request,'base/about.html')

def contact_page(request):
    return render(request,'base/contact.html')
def cart_page(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer)
        items = order.orderproduct_set.all()
        cartItems = order.get_cart_items
        context = {'cartItems': cartItems, 'order': order, 'items': items}
    return render(request, 'base/cart.html', context)


def update_product(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('Product:', productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(
        customer=customer)

    orderItem, created = OrderProduct.objects.get_or_create(
        order=order, product=product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
        product.in_stock = (product.in_stock-1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)
        product.in_stock = (product.in_stock+1)
    elif action == 'remove_all':
        product.in_stock = (product.in_stock+orderItem.quantity)
        orderItem.quantity = 0
    orderItem.save()
    product.save()

    if orderItem.quantity <= 0:
        orderItem.delete()
    return JsonResponse('Item was added', safe=False)



def detail_product(request,pk):
    product=Product.objects.get(id=pk)
    product_the_some_categories = Product.objects.filter(Q(category__name__icontains=product.category)).exclude(Q(
            name__icontains=product.name))
    context = {'product':product,'product_the_some_categories':product_the_some_categories}
    return render(request, 'base/detail_product.html',context)

base/templates/base/about.html
{% extends 'base/main.html' %}
{% block title %} Ecommerce About Page  {% endblock title %}
{% block content %}
  <section id="about-header" class="section-p1">
          <!-- Animation slide-->
          <marquee bgcolor="#ccc" loop="-1" scrollamout="5" width="100%">Ecommerce Website that sell alot of product</marquee>
  </section>
  <section id="about-app" class="section-p1">
    <h1>Download Our</h1>
  </section>
{% endblock content %}

base/templates/base/cart.html
{% extends 'base/main.html' %} {% block title %}Cart Page{% endblock title %} 
{%block content %}
<section id="cart" class="section-p1">
  <table width="100%">
    <tr>
      <th>
        <h5>Items: <strong>{{order.get_cart_items}}</strong></h5>
      </th>
      <th>
        <h5>Total:<strong> ${{order.get_cart_total|floatformat:2}}</strong></h5>
      </th>
    </tr>
  </table>
  <table width="100%">
    <thead>
      <tr>
        <td>Image</td>
        <td>Product</td>
        <td>Price</td>
        <td>Quantity</td>
        <td>Total</td>
      </tr>
    </thead>
    <tbody>
      {% for item in items %}
      <tr>
        <td>
          {%  if item.product.thumnail%}
          <img src="{{item.product.thumbnail.url}}" alt="" />
          {% endif %}
        </td>
        <td>{{item.product.name}}</td>
        <td>${{item.product.price|floatformat:2}}</td>
        <td>
          {{item.quantity}}
          <div>
            {% if item.product.in_stock == 0 %}
            <button class="alert_outStock">&#9652;</button>
            {% else %}
            <button data-product="{{item.product.id}}"data-action="add"class="update-cart normal" style="background-color: #041e42;    color: white;">&#9206;</button>
            {% endif %}
            <button data-product="{{item.product.id}}" data-action="remove" class="update-cart normal" style="background-color:  #a33a3a; color: white;">&#9207;</button>
          </div>
          <button data-product="{{item.product.id}}" data-action="remove_all" class="update-cart normal" style="background-color:  #818ea0;color: white;">Clear</button>
        </td>
        <td>${{item.get_total|floatformat:2}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</section>
<section id="cart-add" class="section-p1">
  <div id="coupon">
    <h3>Apply Coupon</h3>
    <div>
      <input type="text" placeholder="Enter Your Coupon" />
      <button class="normal">Apply</button>
    </div>
  </div>
</section>
{% endblock content %}

base/templates/base/contact.html
{% extends 'base/main.html' %} {% block title %} Ecommerce Contact Page {% endblock title %} 
{% block content %}

<section id="page-header">
  <h2>#let's_talk</h2>
  <p>LEAVE A MESSAGE, We love to hear from you!</p>
</section>
<section id="contact-details" class="section-p1">
  <div class="details">
    <span>GET IN TOUCH</span>
    <h2>Visit one of our agency locations or contact us today</h2>
    <h3>Head Office</h3>
    <div>
      <li>
        <i class="fas fa-map"></i>
        <p>Adsress..., Street..., City...</p>
      </li>
      <li>
        <i class="fas fa-envelope"></i>
        <p>contact@example.com</p>
      </li>
      <li>
        <i class="fas fa-phone-alt"></i>
        <p>contact@example.com</p>
      </li>
      <li>
        <i class="fas fa-clock"></i>
        <p>Monday to Saturday: 9:00am to 16.pm</p>
      </li>
    </div>
  </div>
  <div class="map">
    <iframe
      src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3908.7705869443653!2d104.88850131521953!3d11.568297147239697!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3109519fe4077d69%3A0x20138e822e434660!2z4Z6f4Z624Z6A4Z6b4Z6c4Z634Z6R4Z-S4Z6Z4Z624Z6b4Z-Q4Z6Z4Z6X4Z684Z6Y4Z634Z6T4Z-S4Z6R4Z6X4Z-S4Z6T4Z-G4Z6W4Z-B4Z6J!5e0!3m2!1skm!2skh!4v1673705001416!5m2!1skm!2skh"
      width="600"
      height="450"
      style="border: 0"
      allowfullscreen=""
      loading="lazy"
      referrerpolicy="no-referrer-when-downgrade"
    ></iframe>
  </div>
</section>
<section id="form-details" class="section-p1">
    <form action="">
      <span>LEAVE A MESSAGE</span>
      <h2>We love to hear from you</h2>
      <input type="text" placeholder="Your Name" />
      <input type="text" placeholder="E-mail" />
      <input type="text" placeholder="Subject" />
      <textarea
        name=""
        id=""
        cols="30"
        rows="10"
        placeholder="Your Message"
      ></textarea>
      <button class="normal">Submit</button>
    </form>
    <div class="people">
      <div>
        <p>
          <span>John Doe</span> Senior Marketing Manager <br />Phone: +855 123
          456 7 <br />Email: contact@example.com
        </p>
      </div>
      <div>

          <p>
            <span>John Doe</span> Senior Marketing Manager <br />Phone: +855 123
            456 7 <br />Email: contact@example.com
          </p>
        </div>
        <div>

          <p>
            <span>John Doe</span> Senior Marketing Manager <br />Phone: +855 123
            456 7 <br />Email: contact@example.com
          </p>
        </div>
    </div>
  </section>
{% endblock content %}

base/templates/base/detail_product.html
{% extends 'base/main.html' %} {% block title %} Product Detail Page {% endblock title %}
{% block content %}
<section id="prodetails" class="section-p1">
  <div class="single-pro-image">
    <img src="{{product.thumbnail.url}}" width="80%" id="MainImg" class="af" alt="" />
  </div>
  <div class="single-pro-details">
    <h6>{{product.category}}</h6>
    <h4>{{product.name}}</h4>
    <h2>${{product.price}}</h2>
    {% if product.in_stock == 0 %}
    <button class="normal">Out of Stock</button>
    {% else %}
    {% if request.user.is_authenticated %}
    <button data-product={{product.id}}  data-action="add" class="update-cart addcartBtn">Add To Cart</button>
    {% else %}
    <button class="addcartBtn"> <a style="text-decoration: none; color: white;" href="{% url 'user:login' %}">Add to Cart</a></button>
    {% endif %}
    {% endif %}
    <h4>Product Details</h4>
    <p>{{product.description}}</p>
  </div>
</section>
<section id="product1" class="section-p1">
  <h2>Featured Products</h2>
  <p>Summer Collection New Morden Design</p>
  <div class="pro-container">
    {% for product_the_some_category in product_the_some_categories %}
    <div class="pro">
      <img src="{{product_the_some_category.thumbnail.url}}" alt="#" />
      <div class="des">
        <span>{{product_the_some_category.category}}</span>
        <h5>{{product_the_some_category.name}}</h5>
        <h4>{{product_the_some_category.price}}</h4>
      </div>
      {% if product_the_some_category.in_stock == 0 %}
      <h3>Out of Stock</h3>
      {% else %}
      <button data-product={{product.id}}  data-action="add" class="update-cart addcartBtn">Add to Cart</button>
      {% endif %}
      <button class="viewcartBtn"><a style="text-decoration: none; color: white;" href="{% url 'base:detail_product_page' product_the_some_category.id %}">View Product</a></button>
    </div>
    {% endfor %}
  </div>
</section>

{% endblock content %}

base/templates/base/footer.html
{% load static %}
<footer class="section-p1 footer" >
  <div class="copyright">
    <p>@2023 Ecommerce. All Rights Reserved</p>
    <div >
      <a href=""> Privacy Policy </a>
      <a href=""> Terms of Use </a>
    </div>
  </div>
</footer>

base/templates/base/home.html
{% extends 'base/main.html' %} {% block title %} Ecommerce Website Home Page 
{% endblock title %} 
{% block content %}
  
{% if request.user.is_superuser%}
<section class="section-p1">
  <h4>Tarde-in-offer</h4>
  <h2>Super value deals</h2>
  <h1>On all product</h1>
  <p>Save more with coupons & up to 70% off</p>
</section>
<section id="product1" class="section-p1">
  <h2>New Feature</h2>
  <div class="pro-container">
    {% for product in some_products %}
    <div class="pro">
      {% if product.thumbnail %}
      <img src="{{product.thumbnail.url}}" alt="Product_image" />
      {% endif %}
      <div class="des">
        <span>{{product.category}}</span>
        <h5>{{product.name}}</h5>
        <h4>${{product.price}}</h4>
      </div>
      {% if product.in_stock == 0 %}
      <h3>Out of Stock</h3>
      {% else %}
        {% if request.user.is_authenticated %}
            <button data-product="{{product.id}}"data-action="add"class="update-cart addcartBtn">Add to Cart</button>
        {% else%}
            <button class="addcartBtn">
                <a style="text-decoration: none; color: white;" href="{% url 'user:login' %}">Add to Cart</a>
            </button>
            <button class="viewcartBtn">
              <a style="text-decoration: none; color: white;" href="{% url 'base:detail_product_page' product.id %}">View Product</a>
            </button>
        {% endif %}
      {% endif %}
    </div>
    {% endfor %}
  </div>
</section>
{% else %}
<section id="hero">
  <h4>Tarde-in-offer</h4>
  <h2>Super value deals</h2>
  <h1>On all product</h1>
  <p>Save more with coupons & up to 70% off</p>
  <button><a href="{% url 'base:shop_page' %}">Shop Now</a></button>
</section>
<section id="product1" class="section-p1">
  <h2>New Feature</h2>
  <div class="pro-container">
    {% for product in some_products %}
    <div class="pro">
      {% if product.thumbnail %}
      <img src="{{product.thumbnail.url}}" alt="Product_image" />
      {% endif %}
      <div class="des">
        <span>{{product.category}}</span>
        <h5>{{product.name}}</h5>
        <h4>${{product.price}}</h4>
      </div>
      {% if product.in_stock == 0 %}
      <h3>Out of Stock</h3>
      {% else %}
        {% if request.user.is_authenticated %}
            <button data-product="{{product.id}}"data-action="add"class="update-cart addcartBtn">Add to Cart</button>
        {% else%}
            <button class="addcartBtn">
                <a style="text-decoration: none; color: white;" href="{% url 'user:login' %}">Add to Cart</a>
            </button>
            <button class="viewcartBtn">
              <a style="text-decoration: none; color: white;" href="{% url 'base:detail_product_page' product.id %}">View Product</a>
            </button>
        {% endif %}
      {% endif %}
    </div>
    {% endfor %}
  </div>
</section>
{% endif %}  
{% endblock content %}

base/templates/base/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      href="{% static 'images/cool.png' %}"
      type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}" />
    <title>{% block title %} {% endblock title %}</title>
    <script type="text/javascript">
      const user = "{{request.user}}";
      function getToken(name) {
        var cookieValue = null;
        if (document.cookie !== "") {
          var cookies = document.cookie.split(";");
          for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === name + "=") {
              cookieValue = decodeURIComponent(
                cookie.substring(name.length + 1)
              );
              break;
            }
          }
        }
        return cookieValue;
      }
      var csrftoken = getToken("csrftoken");
    </script>
  </head>
  <body>
   
    {% if request.path == '/login/' or request.path == '/register/' %} 
    
    {% else %}
    {% include 'base/navbar.html' %} 
    {% endif %} 
    {% if messages %}
    <ul>
      {% for message in messages %}
      <li class="messages">{{message}}</li>
      {% endfor %}
    </ul>
    {% endif %}
    <div style="height: 80%">{% block content %}{% endblock content%}</div>

    {% include 'base/footer.html' %}
    <script type="text/javascript">
      var updateBtns = document.getElementsByClassName("update-cart");
      for (var i = 0; i < updateBtns.length; i++) {
        updateBtns[i].addEventListener("click", function () {
          var productId = this.dataset.product;
          var action = this.dataset.action;
          updateUserOrder(productId, action);
        });
      }
      function updateUserOrder(productId, action) {
        console.log("User is authenticated, sending data...");
        fetch("{% url 'base:update_product'%}", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": csrftoken,
          },
          body: JSON.stringify({ productId: productId, action: action }),
        })
          .then((response) => {
            return response.json();
          })
          .then((data) => {
            location.reload();
          });
      }
    </script>
  </body>
</html>

base/templates/base/navbar.html
{% load static %}
<section id="header" >
  <a href="{% url 'base:home_page' %}"><img src="{% static 'images/cool.png' %}" class="logo" alt="logo"/></a>
  <div>
    <ul id="navbar">
      {% if request.user.is_superuser %}
      <li><a href="{% url 'dashboard:index' %}">Dashboard</a></li>
      <li style="font-size: 16px; font-weight: 600; color: #1a1a1a;">{{request.user.username.upper}}</li>
      <li><a href="{% url 'user:logout' %}">Logout</a></li>
      {% else %}
      <li><a href="{% url 'base:home_page' %}">Home</a></li>
      <li><a href="{% url 'base:shop_page' %}">Shop</a></li>
      <li><a href="{% url 'base:about_page' %}">About</a></li>
      <li><a href="{% url 'base:contact_page' %}">Contact</a></li>
      {% if request.user.is_authenticated %} 
      <li id="lg-bag"><a href="{% url 'base:cart_page' %}">Cart</a></li>
      <li style="font-size: 16px; font-weight: 600; color: #1a1a1a;">{{request.user.username.upper}}</li>
      <li><a href="{% url 'user:logout' %}">Logout</a></li>
      {% else %}
      <li><a href="{% url 'user:login' %}">Login</a></li>
      {% endif %} {% endif %}
    </ul>
  </div>
  <div id="mobile">
    <a href="#">Cart</a>
    <i id="bar" class="fas fa-outdent"></i>
  </div>
</section>

base/templates/base/shop.html
{% extends 'base/main.html' %}
{% load static %}
{% block title %} Ecommerce Shop Page  {% endblock title %}
{% block content %}
<section id="product1" class="section-p1">
  <div>
    <form action="" method="GET">
      <input type="text" placeholder="Search..." name="q">
      <button type="submit">Search</button>
    </form>
  </div>
  <ul id="category">
    <li>
      <a href="{% url 'base:shop_page' %}">All</a>
    </li>
    {% for category in categories %}
    <li>
      <a id="ab" href="{% url 'base:shop_page'%}?q={{category.name}}"> {{category.name}} </a>
    </li>
    {% endfor %}
  </ul>
  <div class="pro-container">
    {% for product in page_product %}
    <div class="pro">
      {% if product.thumbnail %}
      <img src="{{product.thumbnail.url}}" alt="Product_image" />
      {% endif %}
      <div class="des">
        <span>{{product.category}}</span>
        <h5>{{product.name}}</h5>
        <h4>${{product.price}}</h4>
      </div>
      {% if product.in_stock == 0 %}
      <h3>Out of Stock</h3>
      {% else %}
      <button data-product={{product.id}}  data-action="add" class="update-cart addcartBtn">Add to Cart</button>
      {% endif %}
      <button class="viewcartBtn"><a style="text-decoration: none; color: white;" href="{% url 'base:detail_product_page' product.id %}">View Product</a></button>
    </div>
    {% endfor %}
  </div>
  <div id="pagination">
    <span>
        {% if page_product.has_previous %}
            <a href="{% url 'base:shop_page' %}?page=1">&laquo; first</a>
            <a href="{% url 'base:shop_page' %}?page={{ page_product.previous_page_number }}">previous</a>
        {% endif %}
        <span id="current">
            Page {{ page_product.number }} of {{ page_product.paginator.num_pages }}
        </span>
        {% if page_product.has_next %}
            <a href="{% url 'base:shop_page' %}?page={{ page_product.next_page_number }}">next</a>
            <a href="{% url 'base:shop_page' %}?page={{ page_product.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</section>
{% endblock content %}